### ISSUE TITLE
No 1.10.2 release despite existence of branch

### ISSUE THREAD

**Issue by Brycey92** [Minebench/watson#5]
I was looking for a release for 1.10.2, but noticed there was none. Surprised that someone would update this mod for every other version but one of the most popular ones, I checked the branches, and you *did* update it, but I guess you forgot to put up a release for it. I could compile this myself, but I'm sure there are others who rely on precompiled builds.

Thanks for updating this mod, though! It's a lifesaver.

**Comment by Phoenix616** [comment]
I've added a build version for 1.10.2, not sure if that's true but it should be identical with the one on [TobiasWooldridge's fork](https://github.com/TobiasWooldridge/watson/releases/tag/1.10.2). Also the latest version (currently 1.12.2) will always be the most popular and supported one ;)

**Comment by Brycey92** [comment]
Wow, that was fast! Thanks!
